# Generated by Django 5.0.1 on 2024-01-17 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('place', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('expense', models.IntegerField()),
                ('note', models.TextField()),
                ('evaluation', models.IntegerField(choices=[(1, 'Bad'), (2, 'Not good'), (3, 'Normal'), (4, 'Good'), (5, 'Very good')], default=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.restaurant')),
            ],
        ),
    ]
